### ISSUE TITLE
Allow to set source and destination folders

### ISSUE THREAD

**Issue by aloboa** [PJDude/dude#12]
I very often want to use dude to compare the contents of an SD to a disk (in which most of files have been copied and distributed across different folders), before cleaning up the SD. For some reason, just adding the 2 directories (SD and drive) and running dude with default options takes a very long time. I presume this is because the (large) drive is searched for duplicates within itself. I would like to run dude so that only files in the SD are searched for duplicates in the disk drive. Perhaps this is possible already with some combination of options, but cannot find them.

**Comment by PJDude** [comment]
That functionality is not available and not compliant with dude design, however:
1. Automatic internal caching mechanism allows user to calculate CRC of "static" files only once. In any future use of dude with the same paths selected (also in different set) all calculated CRC will be used. (Only conditions: same nodeid and same modtime )
2. After scanning "Cross Paths Mode" option will show exactly what You expect.

**Comment by PJDude** [comment]
3. Try to use "exclude from scan" to narrow down scanned space

**Comment by aloboa** [comment]
What a pity you cannot implement this feature, I thought I had finally found the tool for this task. Cannot believe this tool does not exist, as anybody using small disks such as SDs would appreciate making sure all files have been copied before cleaning up a given SD. 
I do use 2, but this implies a long wait for the scan.
Regarding 1 and 3, I will use them until find a better-suited tool.

**Comment by PJDude** [comment]
Best way to _making sure all files have been copied_ is to copy them ;)
