### ISSUE TITLE
High contrast themes on windows 10 makes dude unusable

### ISSUE THREAD

**Issue by junguler** [PJDude/dude#13]
this might be my fault since this happens to a handful of other programs i've used over the years but most programs just look right

![dude_i_cant_see](https://github.com/PJDude/dude/assets/59083599/55f80ed0-6025-479b-bcd5-3ecf0a2e826c)

this is my high contrast theme picture

![colors](https://github.com/PJDude/dude/assets/59083599/6539a00e-0180-4226-b42a-c2de0decf584)

**Comment by PJDude** [comment]
Hi, on latest pre-release try run dude with DUDE_THEME environment variable set to 'alt'. Maybe this will help.

`set DUDE_THEME=alt`
`dude.exe %*`

**Comment by junguler** [comment]
it worked, thank you
