### ISSUE TITLE
GUI: `All Files / Mark Oldest files` mark files that have latest `ctime` 

### ISSUE THREAD

**Issue by Adios** [PJDude/dude#4]
**Describe the bug**
Open GUI, perform a scan, in the CRC groups window, I see 2 copies with the `ctime` field values:
```
2019/07/24 21:27:02
2015/05/17 07:01:15
```
If I right click and select `All Files / Mark Oldest files`, all that are `2019/07/24 21:27:02` will be selected.

**To Reproduce**
1. Open GUI, perform a scan with duplicates exist
2. On the CRC group panel, right click and select `All Files / Mark Oldest files`
3. Files with latest `ctime` are chosen

**Expected behavior**
Since it says `Mark Oldest files`, I think the `2015/05/17 07:01:15` ones should be chosen.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

I am on `Dude-Nuitka Release v1.0361.446`

**Comment by PJDude** [comment]
Fixed on v1.0371.550
Thanks for Your time.
