### ISSUE TITLE
Allow unicode chars in "Exclude from scan" entries

### ISSUE THREAD

**Issue by Adios** [PJDude/dude#5]
**Is your feature request related to a problem? Please describe.**
In the GUI scan window, `Exclude from scan` is useful for duplicates that I want to keep.

But it currently doesn't support unicode input.

If input is not ascii, an error will be shown[^1]:

    scan 'ascii' codec can't encode characters in position NN-NN: ordinal not in range(128)

**Describe the solution you'd like**
It's good to have it support unicode string.

**Additional context**
Tested on `Dude-Nuitka Release v1.0361.446`

----
[^1]: screenshot: https://github.com/PJDude/dude/assets/62105/ed75f4e3-8d21-49e5-9848-a77a4f57f77c

**Comment by PJDude** [comment]
Fixed on v1.0371.550
Thanks for Your time.
