### ISSUE TITLE
Windows: error when deleting `xxx.html` and its connected `xxx_files` folder

### ISSUE THREAD

**Issue by Adios** [PJDude/dude#6]
**Describe the bug**

On Windows, when saving a webpage with Microsoft Edge, the following files will be created:

    a_web_page.html
    a_web_page_files/some.js
    a_web_page_files/some.css
    a_web_page_files/some.jpg
    ....

Using `dude` mark and remove them will result an error when deleting.

I could see `[Errno 2]` or `[Errno 3]` errors in my cases.

    Delete error:[Errno 3] The system cannot find the path specified.: ....

or

    Delete error:[Errno 2] The system cannot find the file specified.: .. ..

Screenshots are attached.

**To Reproduce**

1. on Windows, use Microsoft Edge to save https://github.com/PJDude/dude/releases, file type set to `webpage, full`[^1] 
2. create a folder `1` to hold them
3. make a copy of `1` into `2` [^2]
4. open dude GUI
5. scan folder `1` & `2`
6. mark folder `2`
7. remove marked files
8. error windows pop up, for deleting files and empty folders [^3][^4]

**Expected behavior**

There should be no errors,
and should be able to continue to remove the rest files that are not related with *these html files*

**Desktop (please complete the following information):**

 - OS: Windows 11
 - `Dude v1.0371.550`

**Additional context**

I guess it's related to a weird feature called ***Connected Files*** in Windows.

When you remove a html file, its connected `*_files` folder will also be removed automatically,
so the succeeding deletions in the queue would fail.

I don't know how it is implemented in Windows.
Is it via the syscall so that every deletion will always trigger this behavior?
If so, then we can only skip this kind of errors, I think.

Anyway, I think there should be an option to skip errors during deletion, 
so I can make it continue to go with the rest files without re-scanning and re-marking.

----

Screenshots:
[^1]: download html: https://github.com/PJDude/dude/assets/62105/ce2ad81f-5d52-450a-acd8-cea665c9b040
[^2]: make a dup: https://github.com/PJDude/dude/assets/62105/d84ec025-9bd3-4aa0-8cc3-b8b9b1dd61de
[^3]: deleting error: https://github.com/PJDude/dude/assets/62105/7a4a2a0a-28d2-493c-a859-a7b4655bf52f
[^4]: emptying dir error: https://github.com/PJDude/dude/assets/62105/c9c2f154-f6e0-4a3a-b7e4-1d2c8e1edd48

**Comment by Adios** [comment]
Oh I didn't see it

Now all the *not found errors* are summarize at the end of the process, great!

I think it's a good solution for this windows-specific issue.

Maybe just mention it (how to address windows connected file) somewhere in the documentation and ignore the problem for now. :P

**Comment by PJDude** [comment]
I managed to reproduce the problem on Windows 10 (VM). [Weird](https://www.komodosec.com/post/playing-with-connected-files-a-story-of-mysterious-behavior-in-windows-file-system) indeed, however error appeared only when "Send to Trash ..." option was enabled. Also not-so-good looking error messages like here have been seen when using [send2trash](https://github.com/arsenetar/send2trash/issues/84).

From my point of view, this situation is no different than the case of manual file system manipulation between scanning and files processing. Just a bad idea. It should be and is detected.
